spring.application.name=BackChaskas
server.port=8084

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/icesytembd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=josesas
spring.datasource.password=12345

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# create | update | validate | none
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# HIKARI (POOL DE CONEXIONES)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# JWT
# ===============================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=3600000
